# Generated by Django 4.0.4 on 2022-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gif',
            field=models.ImageField(default='https://online-shopping-page.netlify.app/animation_500_ksx6wx13.gif', upload_to=''),
        ),
    ]
